# Project: practice1
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = practice1.o
LINKOBJ  = practice1.o
LIBS     = -L"C:/Users/a/Desktop/Dev-Cpp/TDM-GCC-64/lib" -L"C:/Users/a/Desktop/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Users/a/Desktop/Dev-Cpp/TDM-GCC-64/include" -I"C:/Users/a/Desktop/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Users/a/Desktop/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"C:/Users/a/Desktop/Dev-Cpp/TDM-GCC-64/include" -I"C:/Users/a/Desktop/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Users/a/Desktop/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Users/a/Desktop/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = practice1.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
DEL      = C:\Users\a\Desktop\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

practice1.o: practice1.c
	$(CC) -c practice1.c -o practice1.o $(CFLAGS)
